#!/bin/csh

#number of nodes:
echo "Results"
echo
echo "------------------------------------------------------------"

#number of threads:
foreach t ( 4 )
    echo NUMT = $t
    foreach p ( 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 )
        echo NUMP = $p
        gcc-7 -std=c99 -DNUMT=$t -DNUMP=$p -o false_sharing false_sharing.c -lm -fopenmp
        ./false_sharing
    end
end
